/*let suggestions = [
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
*/
let suggestions = [
  { name: "Dashboard", link: "student_dash_index.jsp" },
  { name: "User Activity", link: "student_dash_index.jsp" },
  { name: "Payments", link: "student_dash_index.jsp" },
  { name: "New Users", link: "student_dash_index.jsp" },
  { name: "Old Users", link: "student_dash_index.jsp" },
  { name: "List of Hostel", link: "student_dash_index.jsp" },
  { name: "Hostel Details", link: "student_dash_index.jsp" },
  { name: "Profile ", link: "pages-profile.jsp" },
  { name: "Profile Image", link: "pages-profile.jsp" },
  { name: "Update Profile", link: "pages-profile.jsp" },
  { name: "Profile", link: "pages-profile.jsp" },
  { name: "Update Profile Image", link: "pages-profile.jsp" },
  { name: "Users", link: "form-basic.jsp" },
  { name: "List of Users", link: "form-basic.jsp" },
  { name: "User Analytics", link: "form-basic.jsp" },
  { name: "Manage Users", link: "form-basic.jsp" },
  { name: "User Details", link: "form-basic.jsp" },
  { name: "Hostels", link: "table-basic.jsp" },
  { name: "List of Hostels", link: "table-basic.jsp" },
  { name: "Available Hostels", link: "table-basic.jsp" },
  { name: "Hostel Details", link: "table-basic.jsp" },
  { name: "Manage Hostels", link: "table-basic.jsp" },
  { name: "Add Hostel", link: "table-basic.jsp" },
  { name: "Update Hostel", link: "table-basic.jsp" },
  { name: "Packages", link: "icon-material.jsp" },
  { name: "Manage Packages", link: "icon-material.jsp" },
  { name: "Add Package", link: "icon-material.jsp" },
  { name: "Update Package", link: "icon-material.jsp" },
  { name: "Available Packages", link: "icon-material.jsp" },
  { name: "Packages Prices", link: "icon-material.jsp" },
  { name: "Price", link: "icon-material.jsp" },
  { name: "Roles", link: "starter-kit.jsp" },
  { name: "Designation Management", link: "starter-kit.jsp" },
  { name: "Role Management", link: "starter-kit.jsp" },
  { name: "Staff", link: "starter-kit.jsp" },
  { name: "Manage Staff", link: "starter-kit.jsp" },
  { name: "Logout", link: "starter-kit.jsp" }
];