/*let suggestions = [
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
*/
let suggestions = [
  { name: "Dashboard", link: "student_dash_index.jsp" },
  { name: "Hostel Status", link: "student_dash_index.jsp" },
  { name: "My Hostel Details", link: "student_dash_index.jsp" },
  { name: "Profile ", link: "pages-profile.jsp" },
  { name: "Profile Image", link: "pages-profile.jsp" },
  { name: "Update Profile", link: "pages-profile.jsp" },
  { name: "Update Profile Image", link: "pages-profile.jsp" },
  { name: "Manage Mess", link: "table-basic.jsp" },
  { name: "Mess Info", link: "table-basic.jsp" },
  { name: "Mess Menu", link: "table-basic.jsp" },
  { name: "Menu", link: "table-basic.jsp" },
  { name: "Food", link: "table-basic.jsp" },
  { name: "Appetite", link: "table-basic.jsp" },
  { name: "Users", link: "form-basic.jsp" },
  { name: "List of Users", link: "form-basic.jsp" },
  { name: "User Analytics", link: "form-basic.jsp" },
  { name: "Manage Users", link: "form-basic.jsp" },
  { name: "User Details", link: "form-basic.jsp" },
  { name: "Leave Panel", link: "starter-kit.jsp" },
  { name: "Apply Leave", link: "starter-kit.jsp" },
  { name: "Manage Leaves", link: "starter-kit.jsp" },
  { name: "Rec Panel", link: "CRC.jsp" },
  { name: "Manage Request", link: "CRC.jsp" },
  { name: "Report Request", link: "CRC.jsp" },
  { name: "Manage Complain", link: "CRC.jsp" },
  { name: "Report Complain", link: "CRC.jsp" },
  { name: "Manage ReC", link: "CRC.jsp" },
];