/*let suggestions = [
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
*/
let suggestions = [
  { name: "Dashboard", link: "student_dash_index.jsp" },
  { name: "Hostel Status", link: "student_dash_index.jsp" },
  { name: "My Hostel Details", link: "student_dash_index.jsp" },
  { name: "Profile ", link: "pages-profile.jsp" },
  { name: "Profile Image", link: "pages-profile.jsp" },
  { name: "Update Profile", link: "pages-profile.jsp" },
  { name: "Update Profile Image", link: "pages-profile.jsp" },
  { name: "Club Details", link: "form-basic.jsp" },
  { name: "My Clubs", link: "form-basic.jsp" },
  { name: "Sports Events", link: "form-basic.jsp" },
  { name: "Mess Info", link: "table-basic.jsp" },
  { name: "Mess Menu", link: "table-basic.jsp" },
  { name: "Menu", link: "table-basic.jsp" },
  { name: "Food", link: "table-basic.jsp" },
  { name: "Appetite", link: "table-basic.jsp" },
  { name: "Payments", link: "icon-material.jsp" },
  { name: "Payments Panel", link: "icon-material.jsp" },
  { name: "Invoice Download", link: "icon-material.jsp" },
  { name: "My Package Details", link: "icon-material.jsp" },
  { name: "Packages", link: "icon-material.jsp" },
  { name: "Buy Package", link: "icon-material.jsp" },
  { name: "List of Hostel", link: "icon-material.jsp" },
  { name: "Hostel Details", link: "icon-material.jsp" },
  { name: "Available Hostels", link: "icon-material.jsp" },
  { name: "Available Packages", link: "icon-material.jsp" },
  { name: "Packages Prices", link: "icon-material.jsp" },
  { name: "Price", link: "icon-material.jsp" },
  { name: "Leave Panel", link: "starter-kit.jsp" },
  { name: "Apply Leave", link: "starter-kit.jsp" },
  { name: "Manage Leaves", link: "starter-kit.jsp" },
  { name: "Packages Prices", link: "starter-kit.jsp" },
  { name: "Rec Panel", link: "CRC.jsp" },
  { name: "Request", link: "CRC.jsp" },
  { name: "Report Request", link: "CRC.jsp" },
  { name: "Complain", link: "CRC.jsp" },
  { name: "Report Complain", link: "CRC.jsp" },
  { name: "Manage ReC", link: "CRC.jsp" },
];